version: '3.9'

services:
  wordpress:
    image: wordpress
    depends_on:
      - db
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_ENVIRONMENT_TYPE', ${NODE_ENV} );

        @ini_set( 'error_log', '/home/logs/php_error.log' );
        @ini_set( 'log_errors', 'On' );

        if ( WP_ENVIRONMENT_TYPE !== 'production' ){
          define( 'WP_DEBUG', true );
          define( 'WP_DEBUG_DISPLAY', false );
          @ini_set( 'display_errors', 0 );
          define( 'WP_DEBUG_LOG', true );
          define( 'WP_DISABLE_FATAL_ERROR_HANDLER', true );

          define( 'SCRIPT_DEBUG', true );
          define( 'SAVEQUERIES', true );
        }
    volumes:
      - ./packages/theme:/var/www/html/wp-content/themes/aaronsalley
      - .wp/plugins:/var/www/html/wp-content/plugins
      - .wp/uploads:/var/www/html/wp-content/uploads
      - .logs:/home/logs

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ${DB_USER}
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql

volumes:
  dbdata:
