version: '3.9'

services:
  wp_db:
    image: mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
    volumes:
      - sql_data:/var/lib/mysql
  wp:
    image: wordpress
    depends_on:
      - wp_db
    restart: always
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST:-wp_db}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_ENVIRONMENT_TYPE', 'development' );
        define( 'CORE_UPGRADE_SKIP_NEW_BUNDLED', true );
        define( 'WP_DISABLE_FATAL_ERROR_HANDLER', false );   // 5.2 and later
        define( 'WP_DEBUG', false );
        define( 'WP_DEBUG_LOG', false );
        define( 'WP_DEBUG_DISPLAY', false );
        @ini_set( 'display_errors', 'Off' );
        if ( WP_ENVIRONMENT_TYPE !== 'production' ) {
          define( 'SCRIPT_DEBUG', true );
          define( 'WP_DEBUG', true );
          define( 'WP_DEBUG_LOG', true );
          @ini_set( 'log_errors', 'On' );
          @ini_set( 'error_log', '/home/logs/php_error.log' );
        }
        # define( 'FORCE_SSL_ADMIN', true );
        # define( 'WP_HTTP_BLOCK_EXTERNAL', true );
    volumes:
      - ./logs:/home/logs
      - wp_data:/var/www/html
      - ./packages/theme:/var/www/html/wp-content/themes/disruptv
      - ./packages/plugins:/var/www/html/wp-content/plugins
      - ./packages/uploads:/var/www/html/wp-content/uploads
      # - /var/www/html/wp-config

  static:
    build: .
    image: portfolio
    restart: always
    env_file:
      - './.env'

networks:
  default:
volumes:
  sql_data:
  wp_data:
