version: '3.9'

services:
  web_db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: development
      MYSQL_DATABASE: ghost_dev
    volumes:
      - public-data:/var/lib/mysql
    networks:
      - web
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: web_db
      WORDPRESS_DB_PASSWORD: development
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - ./dist:/var/www/html/wp-content/themes/dist
      - wp-content:/var/www/html/wp-content/plugins
      - wp-content:/var/www/html/wp-content/uploads
    networks:
      - web
    depends_on:
      - web_db
  ghost:
    image: ghost
    restart: always
    ports:
      - 3001:2368
    environment:
      database__client: mysql
      database__connection__host: web_db
      database__connection__user: root
      database__connection__password: development
      database__connection__database: ghost_dev
    env_file:
      - './.env'
    volumes:
      - ./dist:/var/lib/ghost/content/themes/devBuild
      - ghost-data:/var/lib/ghost/content
    networks:
      - web

networks:
  web:
volumes:
  public-data:
  wp-content:
  ghost-data:
