# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish to GitHub Pages
run-name: Publishing to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
  MEDIUM_ID: ${{ secrets.MEDIUM_ID }}
  NEXT_PUBLIC_GTM_ID: ${{ secrets.GTM_ID }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install Dependencies
      run: yarn --frozen-lockfile
    - name: Build Next.js
      run: yarn build --if-present
    - name: Push to GitHub Pages
      run: gh-pages -s '**/*' --dotfiles --nojekyll --cname aaronsalley.com -d out
